chore: Rollup & Vitest
prettier/prettier-eslint pull request #1083
Opened 2024-12-07 03:15 UTC by duncanbeevers

### 🗣️ Discussion

This PR is intended to get `prettier-eslint` running on a little more modern testing infrastructure, and to emit CJS and ESM bundles.
Specifically, I'd like to add support for handling newer TypeScript versions and flat configs (re; https://github.com/prettier/prettier-eslint/issues/947, https://github.com/prettier/prettier-eslint/issues/1015, https://github.com/prettier/prettier-eslint/pull/1036,)

### 🔧  Changes

* Use Rollup instead of Babel to generate CJS and ESM bundles
* Convert implementation to ESM
* Use Vitest instead of Jest for tests
* Use memfs instead of mocking specific node:fs functions
* Update nps calls to use CJS config

2025-01-29 19:47 UTC, phun-ky commented
@duncanbeevers can we join forces on this https://github.com/prettier/prettier-eslint/pull/1036, so we can support eslint@9? and @JounQin , could you reopen the PR or will it do it automagically when we push new changes?

2025-01-29 19:59 UTC, duncanbeevers commented
@phun-ky Feel free to port any / all of this over to your PR. I used #1036 as a launching-point for this work, so hopefully it shouldn't be too difficult to reconcile the two.

I'm happy close this PR, or to leave it open until the other PR is resuscitated. Let me know how I can help!

2025-01-30 02:24 UTC, JounQin commented
Great job, and I've reopened #1036

2025-01-30 02:28 UTC, JounQin requested changes

2025-01-30 02:28 UTC, JounQin commented on package.json
>      "@babel/preset-env": "^7.22.9",
These dependencies can be dropped.

2025-01-30 17:33 UTC, duncanbeevers commented on package.json
>      "@babel/preset-env": "^7.22.9",
Are you certain? The options we pass to prettier include `{ parser: 'babel' }`.
If prettier ships with its own babel parser stuff I guess that's fine.

I pushed the PR with the babel dependencies removed, and the tests are passing, so hopefully everything is peachy.

2025-04-11 09:11 UTC, fisker commented on rollup.config.mjs
> +};
Personally, I prefer to use esbuild.

2025-04-11 10:25 UTC, fisker commented on src/utils.mjs
> +    return await import(modulePath).then(
This `import()` will fail on Windows, since it doesn't take Windows path.

2025-05-11 07:41 UTC, closed without merging